aliases:
  # Workflow filters
  - &filter-only-release
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
  - &filter-not-release
    tags:
      ignore: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/

version: 2

jobs:
  mysql-integration-test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/grafana/grafana
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: mysql integration tests
            command: './scripts/mysql-integration-tests.sh'


workflows:
  version: 2
  test:
    jobs:
      - mysql-integration-test
